---
- name: Install and set up grafana on Ubuntu Docker
  hosts: local
  become: yes
  gather_facts: False
  tasks:
    - name: Update apt repo and cache on Ubuntu docker
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - gnupg2
          - curl
          - software-properties-common

    - name: Add the Grafana GPG key
      shell: |
        curl https://packages.grafana.com/gpg.key | apt-key add -
        add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
      args:
        warn: no

    - name: Install the grafana package
      apt:
        name: grafana
        state: present
        update_cache: yes
      notify:
        - Start grafana
        - Enable grafana

    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
      notify: Start and Enable Nginx

    - name: Create grafana nginx config file
      copy:
          dest: /etc/nginx/sites-available/grafana.conf
          mode: 0755
          content: |
            server {
              listen 80;
              server_tokens off;
              client_max_body_size 10M;

              ignore_invalid_headers off;

              location / {
                  send_timeout            90;
                  proxy_read_timeout      900;
                  proxy_send_timeout      90;
                  proxy_connect_timeout   90;
                  proxy_redirect          off;
                  proxy_set_header        Host $host;
                  proxy_set_header        X-Real-IP $remote_addr;
                  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_pass http://127.0.0.1:3000;
              }
            }

    - name: run ln command
      shell: |
        ln -s /etc/nginx/sites-available/grafana.conf /etc/nginx/sites-enabled/grafana.conf
      register: shell_output

    - name: remove default file
      shell: |
        cp /etc/nginx/sites-available/grafana.conf /etc/nginx/conf.d
        chmod 755 /etc/nginx/conf.d/grafana.conf
        rm -rf /etc/nginx/sites-available/default
        rm -rf /etc/nginx/sites-enabled/default
      register: shell_output

  handlers:
    - name: Start grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Start Nginx
      systemd:
        name: nginx
        state: started
