Vagrant.configure("2") do |config|
  config.vm.provider :docker do |d|
     d.build_dir = "."
     d.remains_running = true
     d.has_ssh = true
	 config.ssh.insert_key = false
	 config.ssh.username = 'root'
	 config.ssh.password = 'root'
  end
end
